### PR TITLE
delete dist/* files from repository

### PR DESCRIPTION
**Pull request by elazarcoh**
AFAIK it should not be tracked (and make the git tree cluttered)

### CODE REVIEW

**Comment by alkatar21** [comment]
That sounds like a good plan. I also wanted to clean up and refactor something at some point, but haven't found the time yet to look more closely at JS/TS and VSCode extensions.

**Comment by elazarcoh** [comment]
I would love to help refactoring everything to TS. For me, it is a pain to write with plain JS.

**Comment by alkatar21** [comment]
That is my plan to. Im not shure if @jgclark will support this and since I do not have time currently I have not asked yet. (And # 38 is not merged, which is important, however, as you just pointed out.)
I set up a local dev container, but never got further, since I've only written small TS scripts in ready-made environments so far, I still have to learn how the whole thing works with environments exactly and a few language specifics.

**Comment by jgclark** [comment]
Thanks for the comments, and I'm happy to support your suggestions about TS.

When I took on maintaining this I hardly knew JS, but I've since learned more of that, and now use flow for typing in another project. That was chosen over TS, partly because of the additional complexity of setting up TS for non-professionals (like me). It just means you might need to guide me to how to get going with TS in VSCode, so I can build and test.

**Pull request merged**
