### PR TITLE
add exclude path pattern "**/.vscode-test/**"

### PR DESCRIPTION
**Pull request by buuug7**
when developed with the vscode extensions,  add exclude path pattern "**/.vscode-test/**"

### CODE REVIEW

**Comment by jgclark** [comment]
Thanks for the PR. 
But I'm confused about the purpose. Why should the default be changed to exclude this directory?

**Comment by buuug7** [comment]
@jgclark think why you exclude  node_modules  ？

**Comment by jgclark** [comment]
Remember, I didn't write the code; I maintain the repository, as the history explains.
So please help me understand your point ...

**Comment by buuug7** [comment]
@jgclark merge or not is denpend you, i have not explains with the man who do not write code .

**Review by jgclark — APPROVED** [review]

**Pull request merged**
