### PR TITLE
mac os links with # create new file

### PR DESCRIPTION
**Pull request by zerefdev**
untested

### CODE REVIEW

**Review by jgclark — CHANGES_REQUESTED** [review]
Thanks for the PR, @Zerefdev. 
I think I know what you're trying to do from the code, but please could you say more about it, as I'm not sure why this is about "create new file".
Please also change 'plateform' to 'platform'.

**Comment by jgclark** [comment]
Thanks. I will create the updated .vsix file later, so you can try that locally and see if it works. It's not functionality I've yet used, so my testing won't be very good.

**Comment by jgclark** [comment]
OK, @zerefdev, please download and test the v1.2.4 .vsix locally, and report back.
If you haven't done this before: 
1. go to the Extensions pane, and in the top right corner under the '...' menu there's an option to "Install from VSIX ..." and point it to the new `.vsix` package.
2. re-load VSC to active the new extension.
3. test it.
To revert back to the marketplace version, right-click on the extension and select "Install Another Version ..." which appears to give a list of your previously-installed versions from the marketplace.

**Comment by zerefdev** [comment]
@jgclark works as expected.

https://user-images.githubusercontent.com/25670700/105507822-f4328480-5ccb-11eb-8c09-3ef511766578.mov

**Comment by jgclark** [comment]
Good news, and thanks.
I will push a release to the marketplace shortly.

Do you know JavaScript well? There are some issues raised which I can't fix as I don't know JS well.

**Comment by zerefdev** [comment]
@jgclark yes I do. 
What kind of issues?

**Comment by jgclark** [comment]
(The update is live on the marketplace.)

The issues at https://github.com/jgclark/vscode-todo-highlight/issues
include #12 (Limit the pattern matching to comments) and #13 (border
color only) which need good JavaScript skills.  The other 3 are more about
knowing more about VSCode, which I can probably learn from the
documentation.

It'd be great if you can help with any of these.

**Comment by zerefdev** [comment]
I will see what I can do.

**Pull request merged**
