### PR TITLE
Support creating diagnostics for open files

### PR DESCRIPTION
**Pull request by farwyler**
This adds support for creating diagnostics entries in the problems view.
Entries are only created for opened documents, results from `List Annotated Highlights` are still directed to the output channel. Although this could also be a good starting point for solving #1

### CODE REVIEW

**Review by jgclark — APPROVED** [review]
I'm not familiar with this part of VSCode, but your changes look good so I will merge and try to test and then release.

**Comment by rafaellop** [comment]
How to disable this feature so that todos are not in the 'Problems'? Is there an option for this?

**Comment by farwyler** [comment]
@rafaellop it should be disabled by default. see here
https://github.com/jgclark/vscode-todo-highlight/blob/db9898b05c2866bbc770423a7c9f182711feca25/package.json#L275

**Comment by rafaellop** [comment]
Thanks but I asked how to disable the todos to not show in the Problems tab. I'm migrating a big project and have a tons of todos for the later and I'd prefer to first clean the other problems and work on the todos next. 

An option could be great, in the meanwhile I utilize the filter to hide tem (!TODO)

**Comment by farwyler** [comment]
@rafaellop sorry i misread you question. you can disable problems for specific keywords by setting their `diagnosticSeverity ` to `none`. this should be what you are looking for.

Example:

```json
"todohighlight.keywords": [
    {
        "text": "TODO:",
        "diagnosticSeverity": "none",
        ...
    }
    ...
]
```

**Pull request merged**
